name: QLogger
version: '0.1e-beta'
main: me.harvest.qLogger.QLogger
api-version: '1.21'

commands:
  QLogger:
    aliases:
      - ql
      - logger

    permission: "QLogger.admin"
    description: "main command"
